### ISSUE TITLE
[BUG] Incorrect readings for known words

### ISSUE THREAD

**Issue by sihue** [migaku-official/Migaku-Kanji-Addon#143]
**Describe the bug**
As expected with automatic furigana creation, mistakes will arise every now and again. My cards do actually have a kana field, but the add on isn't set up to leverage that. In this particular case, it is also a matter of sheer frequency. Anyway, since it can get quite distracting, an option to manually correct these mistakes would be appreciated.

**Expected behavior**
Mostly correct readings plus the ability to manually correct occasional mistakes.

**Screenshots**
![seigimasayoshi](https://user-images.githubusercontent.com/67875932/148468854-b403b299-9a65-4787-9418-b194cbf53475.png)

**Comment by saxoncameron** [comment]
Thanks, @sihue - this is on our radar but hadn't been logged yet. I think there's a surprising amount of complexity in a task like this since we'll need to start making distinctions between custom/automatic furigana, add edit dialogues, store that data somewhere.

But not a contentious issue for sure, we'll get it in - priority will depend though.

**Comment by sihue** [comment]
If you do end up storing extra data for example words, it might also be a good idea to add a switch for words that should be displayed on the front. This could work just like marking kanji as known/unknown in the stats window.

**Comment by saxoncameron** [comment]
We already have what you describe there, logged in #114, and on our more "distant" roadmap. Depending on community demand, though, it could get moved forward.

FYI, I have also logged something similar to the "edit" feature that you mention here, just recently:
https://github.com/migaku-official/Migaku-Kanji-Addon/issues/158

**Comment by saxoncameron** [comment]
@sihue I have created a feature request issue (#160) for the ability to "edit" a reading. As mentioned within, I think it makes sense as 1 of 3 related features: edit, star, and ignore/delete. Not sure when we'll do these or what their priority will be, but it's logged, and it won't get buried. 👍 

Closing this bug report, since it's more of a feature request.
